# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ur5_vs/sim_variables.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class sim_variables(genpy.Message):
  _md5sum = "ee6670fc044bef98d1a25a214ff7cacc"
  _type = "ur5_vs/sim_variables"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Bool sim_enable
std_msgs/Bool reconfigure


================================================================================
MSG: std_msgs/Bool
bool data"""
  __slots__ = ['sim_enable','reconfigure']
  _slot_types = ['std_msgs/Bool','std_msgs/Bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sim_enable,reconfigure

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sim_variables, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sim_enable is None:
        self.sim_enable = std_msgs.msg.Bool()
      if self.reconfigure is None:
        self.reconfigure = std_msgs.msg.Bool()
    else:
      self.sim_enable = std_msgs.msg.Bool()
      self.reconfigure = std_msgs.msg.Bool()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.sim_enable.data, _x.reconfigure.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sim_enable is None:
        self.sim_enable = std_msgs.msg.Bool()
      if self.reconfigure is None:
        self.reconfigure = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 2
      (_x.sim_enable.data, _x.reconfigure.data,) = _get_struct_2B().unpack(str[start:end])
      self.sim_enable.data = bool(self.sim_enable.data)
      self.reconfigure.data = bool(self.reconfigure.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.sim_enable.data, _x.reconfigure.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sim_enable is None:
        self.sim_enable = std_msgs.msg.Bool()
      if self.reconfigure is None:
        self.reconfigure = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 2
      (_x.sim_enable.data, _x.reconfigure.data,) = _get_struct_2B().unpack(str[start:end])
      self.sim_enable.data = bool(self.sim_enable.data)
      self.reconfigure.data = bool(self.reconfigure.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
