// Generated by gencpp from file object_detection/image_data.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_MESSAGE_IMAGE_DATA_H
#define OBJECT_DETECTION_MESSAGE_IMAGE_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int64.h>
#include <std_msgs/Int64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace object_detection
{
template <class ContainerAllocator>
struct image_data_
{
  typedef image_data_<ContainerAllocator> Type;

  image_data_()
    : detected_point_x()
    , detected_point_y()
    , detected_point_depth()
    , detected_point_0()
    , detected_point_1()
    , detected_point_2()
    , detected_point_3()
    , detected_point_4()
    , detected_point_5()
    , detected_point_6()
    , detected_point_7()
    , area()  {
    }
  image_data_(const ContainerAllocator& _alloc)
    : detected_point_x(_alloc)
    , detected_point_y(_alloc)
    , detected_point_depth(_alloc)
    , detected_point_0(_alloc)
    , detected_point_1(_alloc)
    , detected_point_2(_alloc)
    , detected_point_3(_alloc)
    , detected_point_4(_alloc)
    , detected_point_5(_alloc)
    , detected_point_6(_alloc)
    , detected_point_7(_alloc)
    , area(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int64_<ContainerAllocator>  _detected_point_x_type;
  _detected_point_x_type detected_point_x;

   typedef  ::std_msgs::Int64_<ContainerAllocator>  _detected_point_y_type;
  _detected_point_y_type detected_point_y;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _detected_point_depth_type;
  _detected_point_depth_type detected_point_depth;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _detected_point_0_type;
  _detected_point_0_type detected_point_0;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _detected_point_1_type;
  _detected_point_1_type detected_point_1;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _detected_point_2_type;
  _detected_point_2_type detected_point_2;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _detected_point_3_type;
  _detected_point_3_type detected_point_3;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _detected_point_4_type;
  _detected_point_4_type detected_point_4;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _detected_point_5_type;
  _detected_point_5_type detected_point_5;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _detected_point_6_type;
  _detected_point_6_type detected_point_6;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _detected_point_7_type;
  _detected_point_7_type detected_point_7;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::object_detection::image_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection::image_data_<ContainerAllocator> const> ConstPtr;

}; // struct image_data_

typedef ::object_detection::image_data_<std::allocator<void> > image_data;

typedef boost::shared_ptr< ::object_detection::image_data > image_dataPtr;
typedef boost::shared_ptr< ::object_detection::image_data const> image_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection::image_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection::image_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_detection::image_data_<ContainerAllocator1> & lhs, const ::object_detection::image_data_<ContainerAllocator2> & rhs)
{
  return lhs.detected_point_x == rhs.detected_point_x &&
    lhs.detected_point_y == rhs.detected_point_y &&
    lhs.detected_point_depth == rhs.detected_point_depth &&
    lhs.detected_point_0 == rhs.detected_point_0 &&
    lhs.detected_point_1 == rhs.detected_point_1 &&
    lhs.detected_point_2 == rhs.detected_point_2 &&
    lhs.detected_point_3 == rhs.detected_point_3 &&
    lhs.detected_point_4 == rhs.detected_point_4 &&
    lhs.detected_point_5 == rhs.detected_point_5 &&
    lhs.detected_point_6 == rhs.detected_point_6 &&
    lhs.detected_point_7 == rhs.detected_point_7 &&
    lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_detection::image_data_<ContainerAllocator1> & lhs, const ::object_detection::image_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::image_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::image_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::image_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::image_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::image_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::image_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection::image_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0116699c5958c8f60e7002f588d8e852";
  }

  static const char* value(const ::object_detection::image_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0116699c5958c8f6ULL;
  static const uint64_t static_value2 = 0x0e7002f588d8e852ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection::image_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection/image_data";
  }

  static const char* value(const ::object_detection::image_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection::image_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int64 detected_point_x\n"
"std_msgs/Int64 detected_point_y\n"
"std_msgs/Float64 detected_point_depth\n"
"std_msgs/Float64 detected_point_0\n"
"std_msgs/Float64 detected_point_1\n"
"std_msgs/Float64 detected_point_2\n"
"std_msgs/Float64 detected_point_3\n"
"std_msgs/Float64 detected_point_4\n"
"std_msgs/Float64 detected_point_5\n"
"std_msgs/Float64 detected_point_6\n"
"std_msgs/Float64 detected_point_7\n"
"std_msgs/Float64 area\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int64\n"
"int64 data\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::object_detection::image_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection::image_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detected_point_x);
      stream.next(m.detected_point_y);
      stream.next(m.detected_point_depth);
      stream.next(m.detected_point_0);
      stream.next(m.detected_point_1);
      stream.next(m.detected_point_2);
      stream.next(m.detected_point_3);
      stream.next(m.detected_point_4);
      stream.next(m.detected_point_5);
      stream.next(m.detected_point_6);
      stream.next(m.detected_point_7);
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct image_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection::image_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection::image_data_<ContainerAllocator>& v)
  {
    s << indent << "detected_point_x: ";
    s << std::endl;
    Printer< ::std_msgs::Int64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_x);
    s << indent << "detected_point_y: ";
    s << std::endl;
    Printer< ::std_msgs::Int64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_y);
    s << indent << "detected_point_depth: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_depth);
    s << indent << "detected_point_0: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_0);
    s << indent << "detected_point_1: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_1);
    s << indent << "detected_point_2: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_2);
    s << indent << "detected_point_3: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_3);
    s << indent << "detected_point_4: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_4);
    s << indent << "detected_point_5: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_5);
    s << indent << "detected_point_6: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_6);
    s << indent << "detected_point_7: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.detected_point_7);
    s << indent << "area: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_MESSAGE_IMAGE_DATA_H
